Bug/ep 358 cpu usage of b one gateway too high subscription fix
btrace-baader/device-opcua-go pull request #22
Opened 2023-06-20 22:20 UTC by MaHaBa22

# PR Checklist

> **If your build fails** due to your commit message not passing the build checks, please review the guidelines [here](https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md).

Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)

## Testing Instructions

1. Connect to opcua device with S7 using no security( no username, no password, Policy= None, Mode= None)
   - Subscriptions will start ( see device opcua container log
   - disconnect the machine -> subscriptions stop
   - reconnect machine-> subscriptions should start again
2. Connect to opcua device with Simotion using security(username, password, Policy = Basic256Sha256, Mode= SignAndEncrypt)
   - Subscriptions will start ( see device opcua container log
   - disconnect the machine -> subscriptions stop
   - reconnect machine-> subscriptions should start again

## New Dependency Instructions (If applicable)

2023-06-21 11:29 UTC, JPLuehrig commented
maybe use at the end of the Initialize the:
     go d.startSubscriber()

2023-06-27 13:39 UTC, mchavezN requested changes

2023-06-27 13:39 UTC, mchavezN commented on internal/driver/subscriptionlistener.go
>  			switch x := res.Value.(type) {
I will suggest renaming the "x" to notification or changeNotification:` switch changeNotification :=` makes it more readable.

2023-06-27 13:39 UTC, mchavezN commented on internal/driver/subscriptionlistener.go
> +func CloseClient(d *Driver, client ClientCloser) error {
What about renaming CloseClientConnection? It is what this function does

2023-06-27 19:17 UTC, MaHaBa22 commented on internal/driver/subscriptionlistener.go
>  			switch x := res.Value.(type) {
makes sense to me

2023-06-27 19:17 UTC, MaHaBa22 commented on internal/driver/subscriptionlistener.go
> +func CloseClient(d *Driver, client ClientCloser) error {
done

2023-06-28 13:57 UTC, mchavezN approved these changes
LGTM

2023-06-30 07:09 UTC, merged